// AFL 2026 Fixture Data - pulled from Squiggle API
// Last updated: 2026-03-26T01:41:30.803289

export interface FixtureGame {
  id: number;
  round: number;
  roundname: string;
  home_team: string | null;
  away_team: string | null;
  home_team_id: number | null;
  away_team_id: number | null;
  venue: string | null;
  date: string;
  home_score: number | null;
  away_score: number | null;
  winner: string | null;
  winner_team_id: number | null;
  complete: boolean;
}

export const AFL_2026_FIXTURE: FixtureGame[] = [
  {
    "id": 38494,
    "round": 0,
    "roundname": "Opening Round",
    "home_team": "Sydney",
    "away_team": "Carlton",
    "home_team_id": 16,
    "away_team_id": 3,
    "venue": "S.C.G.",
    "date": "2026-03-05 19:30:00",
    "home_score": 132,
    "away_score": 69,
    "winner": "Sydney",
    "winner_team_id": 16,
    "complete": true
  },
  {
    "id": 38495,
    "round": 0,
    "roundname": "Opening Round",
    "home_team": "Gold Coast",
    "away_team": "Geelong",
    "home_team_id": 8,
    "away_team_id": 7,
    "venue": "Carrara",
    "date": "2026-03-06 19:05:00",
    "home_score": 125,
    "away_score": 69,
    "winner": "Gold Coast",
    "winner_team_id": 8,
    "complete": true
  },
  {
    "id": 38496,
    "round": 0,
    "roundname": "Opening Round",
    "home_team": "Greater Western Sydney",
    "away_team": "Hawthorn",
    "home_team_id": 9,
    "away_team_id": 10,
    "venue": "Sydney Showground",
    "date": "2026-03-07 16:15:00",
    "home_score": 122,
    "away_score": 95,
    "winner": "Greater Western Sydney",
    "winner_team_id": 9,
    "complete": true
  },
  {
    "id": 38497,
    "round": 0,
    "roundname": "Opening Round",
    "home_team": "Brisbane Lions",
    "away_team": "Western Bulldogs",
    "home_team_id": 2,
    "away_team_id": 18,
    "venue": "Gabba",
    "date": "2026-03-07 18:35:00",
    "home_score": 106,
    "away_score": 111,
    "winner": "Western Bulldogs",
    "winner_team_id": 18,
    "complete": true
  },
  {
    "id": 38498,
    "round": 0,
    "roundname": "Opening Round",
    "home_team": "St Kilda",
    "away_team": "Collingwood",
    "home_team_id": 15,
    "away_team_id": 4,
    "venue": "M.C.G.",
    "date": "2026-03-08 19:20:00",
    "home_score": 66,
    "away_score": 78,
    "winner": "Collingwood",
    "winner_team_id": 4,
    "complete": true
  },
  {
    "id": 38499,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Carlton",
    "away_team": "Richmond",
    "home_team_id": 3,
    "away_team_id": 14,
    "venue": "M.C.G.",
    "date": "2026-03-12 19:30:00",
    "home_score": 75,
    "away_score": 71,
    "winner": "Carlton",
    "winner_team_id": 3,
    "complete": true
  },
  {
    "id": 38500,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Essendon",
    "away_team": "Hawthorn",
    "home_team_id": 5,
    "away_team_id": 10,
    "venue": "M.C.G.",
    "date": "2026-03-13 19:40:00",
    "home_score": 83,
    "away_score": 145,
    "winner": "Hawthorn",
    "winner_team_id": 10,
    "complete": true
  },
  {
    "id": 38501,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Western Bulldogs",
    "away_team": "Greater Western Sydney",
    "home_team_id": 18,
    "away_team_id": 9,
    "venue": "Docklands",
    "date": "2026-03-14 13:15:00",
    "home_score": 134,
    "away_score": 53,
    "winner": "Western Bulldogs",
    "winner_team_id": 18,
    "complete": true
  },
  {
    "id": 38502,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Geelong",
    "away_team": "Fremantle",
    "home_team_id": 7,
    "away_team_id": 6,
    "venue": "Kardinia Park",
    "date": "2026-03-14 16:15:00",
    "home_score": 110,
    "away_score": 100,
    "winner": "Geelong",
    "winner_team_id": 7,
    "complete": true
  },
  {
    "id": 38503,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Sydney",
    "away_team": "Brisbane Lions",
    "home_team_id": 16,
    "away_team_id": 2,
    "venue": "S.C.G.",
    "date": "2026-03-14 19:10:00",
    "home_score": 104,
    "away_score": 60,
    "winner": "Sydney",
    "winner_team_id": 16,
    "complete": true
  },
  {
    "id": 38504,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Collingwood",
    "away_team": "Adelaide",
    "home_team_id": 4,
    "away_team_id": 1,
    "venue": "M.C.G.",
    "date": "2026-03-14 19:35:00",
    "home_score": 79,
    "away_score": 93,
    "winner": "Adelaide",
    "winner_team_id": 1,
    "complete": true
  },
  {
    "id": 38505,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "North Melbourne",
    "away_team": "Port Adelaide",
    "home_team_id": 12,
    "away_team_id": 13,
    "venue": "Docklands",
    "date": "2026-03-15 13:10:00",
    "home_score": 113,
    "away_score": 67,
    "winner": "North Melbourne",
    "winner_team_id": 12,
    "complete": true
  },
  {
    "id": 38506,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Melbourne",
    "away_team": "St Kilda",
    "home_team_id": 11,
    "away_team_id": 15,
    "venue": "M.C.G.",
    "date": "2026-03-15 15:15:00",
    "home_score": 120,
    "away_score": 107,
    "winner": "Melbourne",
    "winner_team_id": 11,
    "complete": true
  },
  {
    "id": 38507,
    "round": 1,
    "roundname": "Round 1",
    "home_team": "Gold Coast",
    "away_team": "West Coast",
    "home_team_id": 8,
    "away_team_id": 17,
    "venue": "Carrara",
    "date": "2026-03-15 17:10:00",
    "home_score": 131,
    "away_score": 72,
    "winner": "Gold Coast",
    "winner_team_id": 8,
    "complete": true
  },
  {
    "id": 38508,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "Hawthorn",
    "away_team": "Sydney",
    "home_team_id": 10,
    "away_team_id": 16,
    "venue": "M.C.G.",
    "date": "2026-03-19 19:30:00",
    "home_score": 99,
    "away_score": 82,
    "winner": "Hawthorn",
    "winner_team_id": 10,
    "complete": true
  },
  {
    "id": 38509,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "Adelaide",
    "away_team": "Western Bulldogs",
    "home_team_id": 1,
    "away_team_id": 18,
    "venue": "Adelaide Oval",
    "date": "2026-03-20 19:10:00",
    "home_score": 88,
    "away_score": 94,
    "winner": "Western Bulldogs",
    "winner_team_id": 18,
    "complete": true
  },
  {
    "id": 38510,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "Richmond",
    "away_team": "Gold Coast",
    "home_team_id": 14,
    "away_team_id": 8,
    "venue": "M.C.G.",
    "date": "2026-03-21 13:15:00",
    "home_score": 60,
    "away_score": 128,
    "winner": "Gold Coast",
    "winner_team_id": 8,
    "complete": true
  },
  {
    "id": 38511,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "Greater Western Sydney",
    "away_team": "St Kilda",
    "home_team_id": 9,
    "away_team_id": 15,
    "venue": "Sydney Showground",
    "date": "2026-03-21 16:15:00",
    "home_score": 74,
    "away_score": 78,
    "winner": "St Kilda",
    "winner_team_id": 15,
    "complete": true
  },
  {
    "id": 38512,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "Fremantle",
    "away_team": "Melbourne",
    "home_team_id": 6,
    "away_team_id": 11,
    "venue": "Perth Stadium",
    "date": "2026-03-21 16:35:00",
    "home_score": 118,
    "away_score": 70,
    "winner": "Fremantle",
    "winner_team_id": 6,
    "complete": true
  },
  {
    "id": 38513,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "Port Adelaide",
    "away_team": "Essendon",
    "home_team_id": 13,
    "away_team_id": 5,
    "venue": "Adelaide Oval",
    "date": "2026-03-22 14:45:00",
    "home_score": 133,
    "away_score": 70,
    "winner": "Port Adelaide",
    "winner_team_id": 13,
    "complete": true
  },
  {
    "id": 38514,
    "round": 2,
    "roundname": "Round 2",
    "home_team": "West Coast",
    "away_team": "North Melbourne",
    "home_team_id": 17,
    "away_team_id": 12,
    "venue": "Perth Stadium",
    "date": "2026-03-22 15:10:00",
    "home_score": 111,
    "away_score": 94,
    "winner": "West Coast",
    "winner_team_id": 17,
    "complete": true
  },
  {
    "id": 38515,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "Geelong",
    "away_team": "Adelaide",
    "home_team_id": 7,
    "away_team_id": 1,
    "venue": "Kardinia Park",
    "date": "2026-03-26 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38516,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "Collingwood",
    "away_team": "Greater Western Sydney",
    "home_team_id": 4,
    "away_team_id": 9,
    "venue": "Docklands",
    "date": "2026-03-27 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38517,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "St Kilda",
    "away_team": "Brisbane Lions",
    "home_team_id": 15,
    "away_team_id": 2,
    "venue": "Docklands",
    "date": "2026-03-28 12:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38518,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "Fremantle",
    "away_team": "Richmond",
    "home_team_id": 6,
    "away_team_id": 14,
    "venue": "Perth Stadium",
    "date": "2026-03-28 13:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38519,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "Essendon",
    "away_team": "North Melbourne",
    "home_team_id": 5,
    "away_team_id": 12,
    "venue": "Docklands",
    "date": "2026-03-28 19:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38520,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "Port Adelaide",
    "away_team": "West Coast",
    "home_team_id": 13,
    "away_team_id": 17,
    "venue": "Adelaide Oval",
    "date": "2026-03-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38521,
    "round": 3,
    "roundname": "Round 3",
    "home_team": "Carlton",
    "away_team": "Melbourne",
    "home_team_id": 3,
    "away_team_id": 11,
    "venue": "M.C.G.",
    "date": "2026-03-29 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38522,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "Brisbane Lions",
    "away_team": "Collingwood",
    "home_team_id": 2,
    "away_team_id": 4,
    "venue": "Gabba",
    "date": "2026-04-02 18:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38523,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "North Melbourne",
    "away_team": "Carlton",
    "home_team_id": 12,
    "away_team_id": 3,
    "venue": "Docklands",
    "date": "2026-04-03 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38524,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "Adelaide",
    "away_team": "Fremantle",
    "home_team_id": 1,
    "away_team_id": 6,
    "venue": "Adelaide Oval",
    "date": "2026-04-03 18:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38525,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "Richmond",
    "away_team": "Port Adelaide",
    "home_team_id": 14,
    "away_team_id": 13,
    "venue": "M.C.G.",
    "date": "2026-04-04 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38526,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "West Coast",
    "away_team": "Sydney",
    "home_team_id": 17,
    "away_team_id": 16,
    "venue": "Perth Stadium",
    "date": "2026-04-04 16:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38527,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "Melbourne",
    "away_team": "Gold Coast",
    "home_team_id": 11,
    "away_team_id": 8,
    "venue": "M.C.G.",
    "date": "2026-04-05 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38528,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "Western Bulldogs",
    "away_team": "Essendon",
    "home_team_id": 18,
    "away_team_id": 5,
    "venue": "Docklands",
    "date": "2026-04-05 19:20:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38529,
    "round": 4,
    "roundname": "Round 4",
    "home_team": "Hawthorn",
    "away_team": "Geelong",
    "home_team_id": 10,
    "away_team_id": 7,
    "venue": "M.C.G.",
    "date": "2026-04-06 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38530,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Adelaide",
    "away_team": "Carlton",
    "home_team_id": 1,
    "away_team_id": 3,
    "venue": "Adelaide Oval",
    "date": "2026-04-09 19:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38531,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Collingwood",
    "away_team": "Fremantle",
    "home_team_id": 4,
    "away_team_id": 6,
    "venue": "Adelaide Oval",
    "date": "2026-04-10 19:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38532,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "North Melbourne",
    "away_team": "Brisbane Lions",
    "home_team_id": 12,
    "away_team_id": 2,
    "venue": "Barossa Park",
    "date": "2026-04-11 12:05:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38533,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Essendon",
    "away_team": "Melbourne",
    "home_team_id": 5,
    "away_team_id": 11,
    "venue": "Adelaide Oval",
    "date": "2026-04-11 12:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38534,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Sydney",
    "away_team": "Gold Coast",
    "home_team_id": 16,
    "away_team_id": 8,
    "venue": "Norwood Oval",
    "date": "2026-04-11 15:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38535,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Hawthorn",
    "away_team": "Western Bulldogs",
    "home_team_id": 10,
    "away_team_id": 18,
    "venue": "Adelaide Oval",
    "date": "2026-04-11 19:05:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38536,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Geelong",
    "away_team": "West Coast",
    "home_team_id": 7,
    "away_team_id": 17,
    "venue": "Norwood Oval",
    "date": "2026-04-12 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38537,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Greater Western Sydney",
    "away_team": "Richmond",
    "home_team_id": 9,
    "away_team_id": 14,
    "venue": "Barossa Park",
    "date": "2026-04-12 14:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38538,
    "round": 5,
    "roundname": "Round 5",
    "home_team": "Port Adelaide",
    "away_team": "St Kilda",
    "home_team_id": 13,
    "away_team_id": 15,
    "venue": "Adelaide Oval",
    "date": "2026-04-12 18:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38539,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Carlton",
    "away_team": "Collingwood",
    "home_team_id": 3,
    "away_team_id": 4,
    "venue": "M.C.G.",
    "date": "2026-04-16 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38540,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Geelong",
    "away_team": "Western Bulldogs",
    "home_team_id": 7,
    "away_team_id": 18,
    "venue": "Kardinia Park",
    "date": "2026-04-17 19:20:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38541,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Sydney",
    "away_team": "Greater Western Sydney",
    "home_team_id": 16,
    "away_team_id": 9,
    "venue": "S.C.G.",
    "date": "2026-04-17 19:50:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38542,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Gold Coast",
    "away_team": "Essendon",
    "home_team_id": 8,
    "away_team_id": 5,
    "venue": "Carrara",
    "date": "2026-04-18 13:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38543,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Hawthorn",
    "away_team": "Port Adelaide",
    "home_team_id": 10,
    "away_team_id": 13,
    "venue": "Docklands",
    "date": "2026-04-18 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38544,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Adelaide",
    "away_team": "St Kilda",
    "home_team_id": 1,
    "away_team_id": 15,
    "venue": "Adelaide Oval",
    "date": "2026-04-18 19:05:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38545,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "North Melbourne",
    "away_team": "Richmond",
    "home_team_id": 12,
    "away_team_id": 14,
    "venue": "Docklands",
    "date": "2026-04-19 13:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38546,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "Melbourne",
    "away_team": "Brisbane Lions",
    "home_team_id": 11,
    "away_team_id": 2,
    "venue": "M.C.G.",
    "date": "2026-04-19 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38547,
    "round": 6,
    "roundname": "Round 6",
    "home_team": "West Coast",
    "away_team": "Fremantle",
    "home_team_id": 17,
    "away_team_id": 6,
    "venue": "Perth Stadium",
    "date": "2026-04-19 15:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38548,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Western Bulldogs",
    "away_team": "Sydney",
    "home_team_id": 18,
    "away_team_id": 16,
    "venue": "Docklands",
    "date": "2026-04-23 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38549,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Richmond",
    "away_team": "Melbourne",
    "home_team_id": 14,
    "away_team_id": 11,
    "venue": "M.C.G.",
    "date": "2026-04-24 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38550,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Hawthorn",
    "away_team": "Gold Coast",
    "home_team_id": 10,
    "away_team_id": 8,
    "venue": "York Park",
    "date": "2026-04-25 12:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38551,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Essendon",
    "away_team": "Collingwood",
    "home_team_id": 5,
    "away_team_id": 4,
    "venue": "M.C.G.",
    "date": "2026-04-25 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38552,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Port Adelaide",
    "away_team": "Geelong",
    "home_team_id": 13,
    "away_team_id": 7,
    "venue": "Adelaide Oval",
    "date": "2026-04-25 18:05:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38553,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Fremantle",
    "away_team": "Carlton",
    "home_team_id": 6,
    "away_team_id": 3,
    "venue": "Perth Stadium",
    "date": "2026-04-25 18:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38554,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "St Kilda",
    "away_team": "West Coast",
    "home_team_id": 15,
    "away_team_id": 17,
    "venue": "Docklands",
    "date": "2026-04-26 13:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38555,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Brisbane Lions",
    "away_team": "Adelaide",
    "home_team_id": 2,
    "away_team_id": 1,
    "venue": "Gabba",
    "date": "2026-04-26 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38556,
    "round": 7,
    "roundname": "Round 7",
    "home_team": "Greater Western Sydney",
    "away_team": "North Melbourne",
    "home_team_id": 9,
    "away_team_id": 12,
    "venue": "Manuka Oval",
    "date": "2026-04-26 16:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38557,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Collingwood",
    "away_team": "Hawthorn",
    "home_team_id": 4,
    "away_team_id": 10,
    "venue": "M.C.G.",
    "date": "2026-04-30 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38558,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Western Bulldogs",
    "away_team": "Fremantle",
    "home_team_id": 18,
    "away_team_id": 6,
    "venue": "Docklands",
    "date": "2026-05-01 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38559,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Adelaide",
    "away_team": "Port Adelaide",
    "home_team_id": 1,
    "away_team_id": 13,
    "venue": "Adelaide Oval",
    "date": "2026-05-01 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38560,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Essendon",
    "away_team": "Brisbane Lions",
    "home_team_id": 5,
    "away_team_id": 2,
    "venue": "Docklands",
    "date": "2026-05-02 12:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38561,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "West Coast",
    "away_team": "Richmond",
    "home_team_id": 17,
    "away_team_id": 14,
    "venue": "Perth Stadium",
    "date": "2026-05-02 14:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38562,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Geelong",
    "away_team": "North Melbourne",
    "home_team_id": 7,
    "away_team_id": 12,
    "venue": "Kardinia Park",
    "date": "2026-05-02 16:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38563,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Carlton",
    "away_team": "St Kilda",
    "home_team_id": 3,
    "away_team_id": 15,
    "venue": "Docklands",
    "date": "2026-05-02 19:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38564,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Sydney",
    "away_team": "Melbourne",
    "home_team_id": 16,
    "away_team_id": 11,
    "venue": "S.C.G.",
    "date": "2026-05-03 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38565,
    "round": 8,
    "roundname": "Round 8",
    "home_team": "Gold Coast",
    "away_team": "Greater Western Sydney",
    "home_team_id": 8,
    "away_team_id": 9,
    "venue": "Carrara",
    "date": "2026-05-03 19:20:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38566,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Fremantle",
    "away_team": "Hawthorn",
    "home_team_id": 6,
    "away_team_id": 10,
    "venue": "Perth Stadium",
    "date": "2026-05-07 18:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38567,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Brisbane Lions",
    "away_team": "Carlton",
    "home_team_id": 2,
    "away_team_id": 3,
    "venue": "Gabba",
    "date": "2026-05-08 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38568,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Port Adelaide",
    "away_team": "Western Bulldogs",
    "home_team_id": 13,
    "away_team_id": 18,
    "venue": "Adelaide Oval",
    "date": "2026-05-08 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38569,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "North Melbourne",
    "away_team": "Sydney",
    "home_team_id": 12,
    "away_team_id": 16,
    "venue": "Docklands",
    "date": "2026-05-09 13:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38570,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Greater Western Sydney",
    "away_team": "Essendon",
    "home_team_id": 9,
    "away_team_id": 5,
    "venue": "Sydney Showground",
    "date": "2026-05-09 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38571,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Gold Coast",
    "away_team": "St Kilda",
    "home_team_id": 8,
    "away_team_id": 15,
    "venue": "Marrara Oval",
    "date": "2026-05-09 18:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38572,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Geelong",
    "away_team": "Collingwood",
    "home_team_id": 7,
    "away_team_id": 4,
    "venue": "M.C.G.",
    "date": "2026-05-09 19:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38573,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Melbourne",
    "away_team": "West Coast",
    "home_team_id": 11,
    "away_team_id": 17,
    "venue": "Docklands",
    "date": "2026-05-10 13:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38574,
    "round": 9,
    "roundname": "Round 9",
    "home_team": "Richmond",
    "away_team": "Adelaide",
    "home_team_id": 14,
    "away_team_id": 1,
    "venue": "M.C.G.",
    "date": "2026-05-10 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38575,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Brisbane Lions",
    "away_team": "Geelong",
    "home_team_id": 2,
    "away_team_id": 7,
    "venue": "Gabba",
    "date": "2026-05-14 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38576,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Sydney",
    "away_team": "Collingwood",
    "home_team_id": 16,
    "away_team_id": 4,
    "venue": "S.C.G.",
    "date": "2026-05-15 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38577,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Gold Coast",
    "away_team": "Port Adelaide",
    "home_team_id": 8,
    "away_team_id": 13,
    "venue": "Marrara Oval",
    "date": "2026-05-15 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38578,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Adelaide",
    "away_team": "North Melbourne",
    "home_team_id": 1,
    "away_team_id": 12,
    "venue": "Adelaide Oval",
    "date": "2026-05-16 12:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38579,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Melbourne",
    "away_team": "Hawthorn",
    "home_team_id": 11,
    "away_team_id": 10,
    "venue": "M.C.G.",
    "date": "2026-05-16 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38580,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Carlton",
    "away_team": "Western Bulldogs",
    "home_team_id": 3,
    "away_team_id": 18,
    "venue": "Docklands",
    "date": "2026-05-16 19:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38581,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "Essendon",
    "away_team": "Fremantle",
    "home_team_id": 5,
    "away_team_id": 6,
    "venue": "M.C.G.",
    "date": "2026-05-17 13:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38582,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "St Kilda",
    "away_team": "Richmond",
    "home_team_id": 15,
    "away_team_id": 14,
    "venue": "Docklands",
    "date": "2026-05-17 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38583,
    "round": 10,
    "roundname": "Round 10",
    "home_team": "West Coast",
    "away_team": "Greater Western Sydney",
    "home_team_id": 17,
    "away_team_id": 9,
    "venue": "Perth Stadium",
    "date": "2026-05-17 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38584,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Hawthorn",
    "away_team": "Adelaide",
    "home_team_id": 10,
    "away_team_id": 1,
    "venue": "York Park",
    "date": "2026-05-21 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38585,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Richmond",
    "away_team": "Essendon",
    "home_team_id": 14,
    "away_team_id": 5,
    "venue": "M.C.G.",
    "date": "2026-05-22 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38586,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Fremantle",
    "away_team": "St Kilda",
    "home_team_id": 6,
    "away_team_id": 15,
    "venue": "Perth Stadium",
    "date": "2026-05-22 18:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38587,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "North Melbourne",
    "away_team": "Gold Coast",
    "home_team_id": 12,
    "away_team_id": 8,
    "venue": "Docklands",
    "date": "2026-05-23 13:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38588,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Geelong",
    "away_team": "Sydney",
    "home_team_id": 7,
    "away_team_id": 16,
    "venue": "Kardinia Park",
    "date": "2026-05-23 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38589,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Collingwood",
    "away_team": "West Coast",
    "home_team_id": 4,
    "away_team_id": 17,
    "venue": "M.C.G.",
    "date": "2026-05-23 16:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38590,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Port Adelaide",
    "away_team": "Carlton",
    "home_team_id": 13,
    "away_team_id": 3,
    "venue": "Adelaide Oval",
    "date": "2026-05-23 19:05:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38591,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Greater Western Sydney",
    "away_team": "Brisbane Lions",
    "home_team_id": 9,
    "away_team_id": 2,
    "venue": "Sydney Showground",
    "date": "2026-05-24 12:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38592,
    "round": 11,
    "roundname": "Round 11",
    "home_team": "Western Bulldogs",
    "away_team": "Melbourne",
    "home_team_id": 18,
    "away_team_id": 11,
    "venue": "Docklands",
    "date": "2026-05-24 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38593,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "St Kilda",
    "away_team": "Hawthorn",
    "home_team_id": 15,
    "away_team_id": 10,
    "venue": "Docklands",
    "date": "2026-05-28 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38594,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "Carlton",
    "away_team": "Geelong",
    "home_team_id": 3,
    "away_team_id": 7,
    "venue": "M.C.G.",
    "date": "2026-05-29 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38595,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "Sydney",
    "away_team": "Richmond",
    "home_team_id": 16,
    "away_team_id": 14,
    "venue": "S.C.G.",
    "date": "2026-05-30 13:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38596,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "Brisbane Lions",
    "away_team": "Fremantle",
    "home_team_id": 2,
    "away_team_id": 6,
    "venue": "Gabba",
    "date": "2026-05-30 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38597,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "Western Bulldogs",
    "away_team": "Collingwood",
    "home_team_id": 18,
    "away_team_id": 4,
    "venue": "Docklands",
    "date": "2026-05-30 19:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38598,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "Melbourne",
    "away_team": "Greater Western Sydney",
    "home_team_id": 11,
    "away_team_id": 9,
    "venue": "Traeger Park",
    "date": "2026-05-31 14:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38599,
    "round": 12,
    "roundname": "Round 12",
    "home_team": "West Coast",
    "away_team": "Essendon",
    "home_team_id": 17,
    "away_team_id": 5,
    "venue": "Perth Stadium",
    "date": "2026-05-31 17:20:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38600,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "Adelaide",
    "away_team": "Geelong",
    "home_team_id": 1,
    "away_team_id": 7,
    "venue": "Adelaide Oval",
    "date": "2026-06-04 19:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38601,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "Hawthorn",
    "away_team": "Western Bulldogs",
    "home_team_id": 10,
    "away_team_id": 18,
    "venue": "M.C.G.",
    "date": "2026-06-05 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38602,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "North Melbourne",
    "away_team": "Fremantle",
    "home_team_id": 12,
    "away_team_id": 6,
    "venue": "Hands Oval",
    "date": "2026-06-06 12:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38603,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "Gold Coast",
    "away_team": "Brisbane Lions",
    "home_team_id": 8,
    "away_team_id": 2,
    "venue": "Carrara",
    "date": "2026-06-06 17:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38604,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "West Coast",
    "away_team": "Port Adelaide",
    "home_team_id": 17,
    "away_team_id": 13,
    "venue": "Perth Stadium",
    "date": "2026-06-06 18:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38605,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "Sydney",
    "away_team": "St Kilda",
    "home_team_id": 16,
    "away_team_id": 15,
    "venue": "S.C.G.",
    "date": "2026-06-07 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38606,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "Essendon",
    "away_team": "Carlton",
    "home_team_id": 5,
    "away_team_id": 3,
    "venue": "M.C.G.",
    "date": "2026-06-07 19:20:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38607,
    "round": 13,
    "roundname": "Round 13",
    "home_team": "Collingwood",
    "away_team": "Melbourne",
    "home_team_id": 4,
    "away_team_id": 11,
    "venue": "M.C.G.",
    "date": "2026-06-08 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38608,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "Western Bulldogs",
    "away_team": "Adelaide",
    "home_team_id": 18,
    "away_team_id": 1,
    "venue": "Docklands",
    "date": "2026-06-11 19:30:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38609,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "Geelong",
    "away_team": "Gold Coast",
    "home_team_id": 7,
    "away_team_id": 8,
    "venue": "Kardinia Park",
    "date": "2026-06-12 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38610,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "Melbourne",
    "away_team": "Essendon",
    "home_team_id": 11,
    "away_team_id": 5,
    "venue": "M.C.G.",
    "date": "2026-06-13 13:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38611,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "North Melbourne",
    "away_team": "West Coast",
    "home_team_id": 12,
    "away_team_id": 17,
    "venue": "Perth Stadium",
    "date": "2026-06-13 14:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38612,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "Port Adelaide",
    "away_team": "Sydney",
    "home_team_id": 13,
    "away_team_id": 16,
    "venue": "Adelaide Oval",
    "date": "2026-06-13 19:05:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38613,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "Richmond",
    "away_team": "Brisbane Lions",
    "home_team_id": 14,
    "away_team_id": 2,
    "venue": "Bellerive Oval",
    "date": "2026-06-14 13:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38614,
    "round": 14,
    "roundname": "Round 14",
    "home_team": "St Kilda",
    "away_team": "Greater Western Sydney",
    "home_team_id": 15,
    "away_team_id": 9,
    "venue": "Docklands",
    "date": "2026-06-14 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38615,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "Fremantle",
    "away_team": "Geelong",
    "home_team_id": 6,
    "away_team_id": 7,
    "venue": "Perth Stadium",
    "date": "2026-06-18 18:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38616,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "Gold Coast",
    "away_team": "Hawthorn",
    "home_team_id": 8,
    "away_team_id": 10,
    "venue": "Carrara",
    "date": "2026-06-19 19:40:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38617,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "Adelaide",
    "away_team": "Melbourne",
    "home_team_id": 1,
    "away_team_id": 11,
    "venue": "Adelaide Oval",
    "date": "2026-06-20 12:45:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38618,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "Greater Western Sydney",
    "away_team": "Carlton",
    "home_team_id": 9,
    "away_team_id": 3,
    "venue": "Sydney Showground",
    "date": "2026-06-20 16:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38619,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "Collingwood",
    "away_team": "Port Adelaide",
    "home_team_id": 4,
    "away_team_id": 13,
    "venue": "M.C.G.",
    "date": "2026-06-20 19:35:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38620,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "Richmond",
    "away_team": "North Melbourne",
    "home_team_id": 14,
    "away_team_id": 12,
    "venue": "M.C.G.",
    "date": "2026-06-21 13:10:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38621,
    "round": 15,
    "roundname": "Round 15",
    "home_team": "St Kilda",
    "away_team": "Western Bulldogs",
    "home_team_id": 15,
    "away_team_id": 18,
    "venue": "Docklands",
    "date": "2026-06-21 15:15:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38622,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "Brisbane Lions",
    "away_team": "Sydney",
    "home_team_id": 2,
    "away_team_id": 16,
    "venue": "Gabba",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38623,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "Carlton",
    "away_team": "West Coast",
    "home_team_id": 3,
    "away_team_id": 17,
    "venue": "Docklands",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38624,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "Collingwood",
    "away_team": "Richmond",
    "home_team_id": 4,
    "away_team_id": 14,
    "venue": "M.C.G.",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38625,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "Hawthorn",
    "away_team": "Greater Western Sydney",
    "home_team_id": 10,
    "away_team_id": 9,
    "venue": "M.C.G.",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38626,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "North Melbourne",
    "away_team": "Essendon",
    "home_team_id": 12,
    "away_team_id": 5,
    "venue": "Docklands",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38627,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "Port Adelaide",
    "away_team": "Adelaide",
    "home_team_id": 13,
    "away_team_id": 1,
    "venue": "Adelaide Oval",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38628,
    "round": 16,
    "roundname": "Round 16",
    "home_team": "Fremantle",
    "away_team": "Gold Coast",
    "home_team_id": 6,
    "away_team_id": 8,
    "venue": "Perth Stadium",
    "date": "2026-06-22 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38629,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Essendon",
    "away_team": "St Kilda",
    "home_team_id": 5,
    "away_team_id": 15,
    "venue": "Docklands",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38630,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Geelong",
    "away_team": "Brisbane Lions",
    "home_team_id": 7,
    "away_team_id": 2,
    "venue": "Kardinia Park",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38631,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Gold Coast",
    "away_team": "Collingwood",
    "home_team_id": 8,
    "away_team_id": 4,
    "venue": "Carrara",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38632,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Greater Western Sydney",
    "away_team": "Fremantle",
    "home_team_id": 9,
    "away_team_id": 6,
    "venue": "Manuka Oval",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38633,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Hawthorn",
    "away_team": "Melbourne",
    "home_team_id": 10,
    "away_team_id": 11,
    "venue": "York Park",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38634,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Richmond",
    "away_team": "Carlton",
    "home_team_id": 14,
    "away_team_id": 3,
    "venue": "M.C.G.",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38635,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Sydney",
    "away_team": "Western Bulldogs",
    "home_team_id": 16,
    "away_team_id": 18,
    "venue": "S.C.G.",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38636,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "Port Adelaide",
    "away_team": "North Melbourne",
    "home_team_id": 13,
    "away_team_id": 12,
    "venue": "Adelaide Oval",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38637,
    "round": 17,
    "roundname": "Round 17",
    "home_team": "West Coast",
    "away_team": "Adelaide",
    "home_team_id": 17,
    "away_team_id": 1,
    "venue": "Perth Stadium",
    "date": "2026-06-29 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38638,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Brisbane Lions",
    "away_team": "Essendon",
    "home_team_id": 2,
    "away_team_id": 5,
    "venue": "Gabba",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38639,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Carlton",
    "away_team": "Hawthorn",
    "home_team_id": 3,
    "away_team_id": 10,
    "venue": "M.C.G.",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38640,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Collingwood",
    "away_team": "North Melbourne",
    "home_team_id": 4,
    "away_team_id": 12,
    "venue": "Docklands",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38641,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Greater Western Sydney",
    "away_team": "Geelong",
    "home_team_id": 9,
    "away_team_id": 7,
    "venue": "Sydney Showground",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38642,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Melbourne",
    "away_team": "Richmond",
    "home_team_id": 11,
    "away_team_id": 14,
    "venue": "M.C.G.",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38643,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "St Kilda",
    "away_team": "Port Adelaide",
    "home_team_id": 15,
    "away_team_id": 13,
    "venue": "Docklands",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38644,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Western Bulldogs",
    "away_team": "West Coast",
    "home_team_id": 18,
    "away_team_id": 17,
    "venue": "Docklands",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38645,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Adelaide",
    "away_team": "Gold Coast",
    "home_team_id": 1,
    "away_team_id": 8,
    "venue": "Adelaide Oval",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38646,
    "round": 18,
    "roundname": "Round 18",
    "home_team": "Fremantle",
    "away_team": "Sydney",
    "home_team_id": 6,
    "away_team_id": 16,
    "venue": "Perth Stadium",
    "date": "2026-07-06 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38647,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Collingwood",
    "away_team": "Carlton",
    "home_team_id": 4,
    "away_team_id": 3,
    "venue": "M.C.G.",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38648,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Essendon",
    "away_team": "Greater Western Sydney",
    "home_team_id": 5,
    "away_team_id": 9,
    "venue": "Docklands",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38649,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Geelong",
    "away_team": "St Kilda",
    "home_team_id": 7,
    "away_team_id": 15,
    "venue": "Kardinia Park",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38650,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Gold Coast",
    "away_team": "Western Bulldogs",
    "home_team_id": 8,
    "away_team_id": 18,
    "venue": "Carrara",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38651,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "North Melbourne",
    "away_team": "Melbourne",
    "home_team_id": 12,
    "away_team_id": 11,
    "venue": "Docklands",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38652,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Richmond",
    "away_team": "Hawthorn",
    "home_team_id": 14,
    "away_team_id": 10,
    "venue": "M.C.G.",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38653,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Sydney",
    "away_team": "Adelaide",
    "home_team_id": 16,
    "away_team_id": 1,
    "venue": "S.C.G.",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38654,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "Port Adelaide",
    "away_team": "Fremantle",
    "home_team_id": 13,
    "away_team_id": 6,
    "venue": "Adelaide Oval",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38655,
    "round": 19,
    "roundname": "Round 19",
    "home_team": "West Coast",
    "away_team": "Brisbane Lions",
    "home_team_id": 17,
    "away_team_id": 2,
    "venue": "Perth Stadium",
    "date": "2026-07-13 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38656,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Brisbane Lions",
    "away_team": "Port Adelaide",
    "home_team_id": 2,
    "away_team_id": 13,
    "venue": "Gabba",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38657,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Carlton",
    "away_team": "Gold Coast",
    "home_team_id": 3,
    "away_team_id": 8,
    "venue": "Docklands",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38658,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Greater Western Sydney",
    "away_team": "Sydney",
    "home_team_id": 9,
    "away_team_id": 16,
    "venue": "Sydney Showground",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38659,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Hawthorn",
    "away_team": "Essendon",
    "home_team_id": 10,
    "away_team_id": 5,
    "venue": "M.C.G.",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38661,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Melbourne",
    "away_team": "Geelong",
    "home_team_id": 11,
    "away_team_id": 7,
    "venue": "M.C.G.",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38660,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "North Melbourne",
    "away_team": "St Kilda",
    "home_team_id": 12,
    "away_team_id": 15,
    "venue": "Docklands",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38662,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Western Bulldogs",
    "away_team": "Richmond",
    "home_team_id": 18,
    "away_team_id": 14,
    "venue": "Docklands",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38663,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Adelaide",
    "away_team": "Collingwood",
    "home_team_id": 1,
    "away_team_id": 4,
    "venue": "Adelaide Oval",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38664,
    "round": 20,
    "roundname": "Round 20",
    "home_team": "Fremantle",
    "away_team": "West Coast",
    "home_team_id": 6,
    "away_team_id": 17,
    "venue": "Perth Stadium",
    "date": "2026-07-20 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38665,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Carlton",
    "away_team": "Brisbane Lions",
    "home_team_id": 3,
    "away_team_id": 2,
    "venue": "Docklands",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38666,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Collingwood",
    "away_team": "Geelong",
    "home_team_id": 4,
    "away_team_id": 7,
    "venue": "M.C.G.",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38667,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Essendon",
    "away_team": "Adelaide",
    "home_team_id": 5,
    "away_team_id": 1,
    "venue": "Docklands",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38668,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Gold Coast",
    "away_team": "Melbourne",
    "home_team_id": 8,
    "away_team_id": 11,
    "venue": "Carrara",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38669,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Hawthorn",
    "away_team": "North Melbourne",
    "home_team_id": 10,
    "away_team_id": 12,
    "venue": "York Park",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38670,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Richmond",
    "away_team": "West Coast",
    "home_team_id": 14,
    "away_team_id": 17,
    "venue": "M.C.G.",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38671,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "St Kilda",
    "away_team": "Sydney",
    "home_team_id": 15,
    "away_team_id": 16,
    "venue": "Docklands",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38672,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Port Adelaide",
    "away_team": "Greater Western Sydney",
    "home_team_id": 13,
    "away_team_id": 9,
    "venue": "Adelaide Oval",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38673,
    "round": 21,
    "roundname": "Round 21",
    "home_team": "Fremantle",
    "away_team": "Western Bulldogs",
    "home_team_id": 6,
    "away_team_id": 18,
    "venue": "Perth Stadium",
    "date": "2026-07-27 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38674,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Brisbane Lions",
    "away_team": "Hawthorn",
    "home_team_id": 2,
    "away_team_id": 10,
    "venue": "Gabba",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38675,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Geelong",
    "away_team": "Essendon",
    "home_team_id": 7,
    "away_team_id": 5,
    "venue": "Kardinia Park",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38676,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Greater Western Sydney",
    "away_team": "Gold Coast",
    "home_team_id": 9,
    "away_team_id": 8,
    "venue": "Manuka Oval",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38677,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Melbourne",
    "away_team": "Fremantle",
    "home_team_id": 11,
    "away_team_id": 6,
    "venue": "M.C.G.",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38678,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "St Kilda",
    "away_team": "Carlton",
    "home_team_id": 15,
    "away_team_id": 3,
    "venue": "Docklands",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38679,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Sydney",
    "away_team": "Port Adelaide",
    "home_team_id": 16,
    "away_team_id": 13,
    "venue": "S.C.G.",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38680,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Western Bulldogs",
    "away_team": "North Melbourne",
    "home_team_id": 18,
    "away_team_id": 12,
    "venue": "Docklands",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38681,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "Adelaide",
    "away_team": "Richmond",
    "home_team_id": 1,
    "away_team_id": 14,
    "venue": "Adelaide Oval",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38682,
    "round": 22,
    "roundname": "Round 22",
    "home_team": "West Coast",
    "away_team": "Collingwood",
    "home_team_id": 17,
    "away_team_id": 4,
    "venue": "Perth Stadium",
    "date": "2026-08-03 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38683,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Brisbane Lions",
    "away_team": "Gold Coast",
    "home_team_id": 2,
    "away_team_id": 8,
    "venue": "Gabba",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38684,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Essendon",
    "away_team": "Sydney",
    "home_team_id": 5,
    "away_team_id": 16,
    "venue": "M.C.G.",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38685,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Greater Western Sydney",
    "away_team": "West Coast",
    "home_team_id": 9,
    "away_team_id": 17,
    "venue": "Sydney Showground",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38686,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Hawthorn",
    "away_team": "Collingwood",
    "home_team_id": 10,
    "away_team_id": 4,
    "venue": "M.C.G.",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38687,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "North Melbourne",
    "away_team": "Geelong",
    "home_team_id": 12,
    "away_team_id": 7,
    "venue": "Docklands",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38688,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Richmond",
    "away_team": "St Kilda",
    "home_team_id": 14,
    "away_team_id": 15,
    "venue": "M.C.G.",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38689,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Western Bulldogs",
    "away_team": "Carlton",
    "home_team_id": 18,
    "away_team_id": 3,
    "venue": "Docklands",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38690,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Port Adelaide",
    "away_team": "Melbourne",
    "home_team_id": 13,
    "away_team_id": 11,
    "venue": "Adelaide Oval",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38691,
    "round": 23,
    "roundname": "Round 23",
    "home_team": "Fremantle",
    "away_team": "Adelaide",
    "home_team_id": 6,
    "away_team_id": 1,
    "venue": "Perth Stadium",
    "date": "2026-08-10 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38693,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Carlton",
    "away_team": "Fremantle",
    "home_team_id": 3,
    "away_team_id": 6,
    "venue": "Docklands",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38692,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Collingwood",
    "away_team": "Brisbane Lions",
    "home_team_id": 4,
    "away_team_id": 2,
    "venue": "M.C.G.",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38694,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Essendon",
    "away_team": "Port Adelaide",
    "home_team_id": 5,
    "away_team_id": 13,
    "venue": "Docklands",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38695,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Geelong",
    "away_team": "Richmond",
    "home_team_id": 7,
    "away_team_id": 14,
    "venue": "Kardinia Park",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38696,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Melbourne",
    "away_team": "Western Bulldogs",
    "home_team_id": 11,
    "away_team_id": 18,
    "venue": "M.C.G.",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38697,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "St Kilda",
    "away_team": "Gold Coast",
    "home_team_id": 15,
    "away_team_id": 8,
    "venue": "Docklands",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38698,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Sydney",
    "away_team": "North Melbourne",
    "home_team_id": 16,
    "away_team_id": 12,
    "venue": "S.C.G.",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38699,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "Adelaide",
    "away_team": "Greater Western Sydney",
    "home_team_id": 1,
    "away_team_id": 9,
    "venue": "Adelaide Oval",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38700,
    "round": 24,
    "roundname": "Round 24",
    "home_team": "West Coast",
    "away_team": "Hawthorn",
    "home_team_id": 17,
    "away_team_id": 10,
    "venue": "Perth Stadium",
    "date": "2026-08-17 12:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38710,
    "round": 25,
    "roundname": "Finals Week 1",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-04 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38711,
    "round": 25,
    "roundname": "Finals Week 1",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-04 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38712,
    "round": 25,
    "roundname": "Finals Week 1",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-04 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38713,
    "round": 25,
    "roundname": "Finals Week 1",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-04 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38714,
    "round": 26,
    "roundname": "Semi-Finals",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-11 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38715,
    "round": 26,
    "roundname": "Semi-Finals",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-11 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38716,
    "round": 27,
    "roundname": "Preliminary Finals",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-18 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38717,
    "round": 27,
    "roundname": "Preliminary Finals",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-18 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  },
  {
    "id": 38718,
    "round": 28,
    "roundname": "Grand Final",
    "home_team": null,
    "away_team": null,
    "home_team_id": null,
    "away_team_id": null,
    "venue": "M.C.G.",
    "date": "2026-09-25 14:00:00",
    "home_score": 0,
    "away_score": 0,
    "winner": null,
    "winner_team_id": null,
    "complete": false
  }
];

export const TOTAL_GAMES = 216;
export const TOTAL_ROUNDS = 28;

export const ROUND_SUMMARY = [
  {
    "round": 0,
    "name": "Opening Round",
    "games": 5,
    "completed": 5
  },
  {
    "round": 1,
    "name": "Round 1",
    "games": 9,
    "completed": 9
  },
  {
    "round": 2,
    "name": "Round 2",
    "games": 7,
    "completed": 7
  },
  {
    "round": 3,
    "name": "Round 3",
    "games": 7,
    "completed": 0
  },
  {
    "round": 4,
    "name": "Round 4",
    "games": 8,
    "completed": 0
  },
  {
    "round": 5,
    "name": "Round 5",
    "games": 9,
    "completed": 0
  },
  {
    "round": 6,
    "name": "Round 6",
    "games": 9,
    "completed": 0
  },
  {
    "round": 7,
    "name": "Round 7",
    "games": 9,
    "completed": 0
  },
  {
    "round": 8,
    "name": "Round 8",
    "games": 9,
    "completed": 0
  },
  {
    "round": 9,
    "name": "Round 9",
    "games": 9,
    "completed": 0
  },
  {
    "round": 10,
    "name": "Round 10",
    "games": 9,
    "completed": 0
  },
  {
    "round": 11,
    "name": "Round 11",
    "games": 9,
    "completed": 0
  },
  {
    "round": 12,
    "name": "Round 12",
    "games": 7,
    "completed": 0
  },
  {
    "round": 13,
    "name": "Round 13",
    "games": 8,
    "completed": 0
  },
  {
    "round": 14,
    "name": "Round 14",
    "games": 7,
    "completed": 0
  },
  {
    "round": 15,
    "name": "Round 15",
    "games": 7,
    "completed": 0
  },
  {
    "round": 16,
    "name": "Round 16",
    "games": 7,
    "completed": 0
  },
  {
    "round": 17,
    "name": "Round 17",
    "games": 9,
    "completed": 0
  },
  {
    "round": 18,
    "name": "Round 18",
    "games": 9,
    "completed": 0
  },
  {
    "round": 19,
    "name": "Round 19",
    "games": 9,
    "completed": 0
  },
  {
    "round": 20,
    "name": "Round 20",
    "games": 9,
    "completed": 0
  },
  {
    "round": 21,
    "name": "Round 21",
    "games": 9,
    "completed": 0
  },
  {
    "round": 22,
    "name": "Round 22",
    "games": 9,
    "completed": 0
  },
  {
    "round": 23,
    "name": "Round 23",
    "games": 9,
    "completed": 0
  },
  {
    "round": 24,
    "name": "Round 24",
    "games": 9,
    "completed": 0
  },
  {
    "round": 25,
    "name": "Finals Week 1",
    "games": 4,
    "completed": 0
  },
  {
    "round": 26,
    "name": "Semi-Finals",
    "games": 2,
    "completed": 0
  },
  {
    "round": 27,
    "name": "Preliminary Finals",
    "games": 2,
    "completed": 0
  },
  {
    "round": 28,
    "name": "Grand Final",
    "games": 1,
    "completed": 0
  }
];
